README.md

update readme typo in URL link

---

PopPUNK/__main__.py
PopPUNK/models.py
PopPUNK/refine.py

Improved default model refinement range

---

PopPUNK/__main__.py
PopPUNK/assign.py
PopPUNK/visualise.py
scripts/poppunk_easy_run.py
setup.py
test/run_test.py

After this I am happy with the CLI, so will close #73 for now
Implements comments on #112

Update CLI defaults to be simpler

---

PopPUNK/assign.py

Save the full distance matrix with assign

---

docs/setup.py
environment.yml
setup.py

Still including requirements. Trying to remove them completely

Attempt to fix readthedocs builds

---

PopPUNK/sketchlib.py
PopPUNK/utils.py

Correcting a small omission in the QC filtering.

Fix to QC function

---

PopPUNK/plot.py
PopPUNK/visualise.py
test/run_test.py

Was currently using all available cores (rapidnj default)

Specify rapidnj's threads

---

PopPUNK/plot.py
PopPUNK/visualise.py
azure-pipelines.yml
test/run_test.py

Because I forgot to approve the rapidnj PR.

Update MST branch with changes to master

---

PopPUNK/__main__.py
PopPUNK/assign.py
PopPUNK/bgmm.py
PopPUNK/dbscan.py
PopPUNK/models.py
PopPUNK/network.py
PopPUNK/plot.py
PopPUNK/refine.py
PopPUNK/utils.py
PopPUNK/visualise.py
poppunk_assign-runner.py

- Processes in blocks, which keeps memory usage down
- Adds a progress bar
TODO:

DBSCAN and BGMM assignment improvements

---

PopPUNK/models.py
docs/scripts.rst
environment.yml
scripts/poppunk_calculate_rand_indices.py

sklearn has made some changes to its cluster modules, so I have just updated the paths

Fix older scripts

---

PopPUNK/__init__.py
PopPUNK/__main__.py
PopPUNK/assign.py
PopPUNK/models.py
PopPUNK/network.py
PopPUNK/refine.py
PopPUNK/sketchlib.py
PopPUNK/utils.py
PopPUNK/web.py
docs/model_fitting.rst
docs/requirements.txt
docs/scripts.rst
environment.yml
scripts/poppunk_iterate.py
setup.py
test/run_test.py
test/test-web.py

This implements the 'enhanced PopPUNK' method by Bin and Daniel.
TODO:

Multi-boundary method

---

docker2/Dockerfile
environment.yml

Rapidnj installation was added to Dockerfile

Add rapidnj to docker image

---

PopPUNK/mandrake.py
PopPUNK/sketchlib.py
docker2/Dockerfile
environment.yml
scripts/poppunk_distribute_fit.py

Also pin joblib version to fix CI for now
Closes #231

Patch for relative paths in plot fit

---

PopPUNK/assign.py
PopPUNK/network.py

Was trying to use wrong boundary with models fitted as `--threshold`

Fix for assign with threshold models

---

PopPUNK/__init__.py
PopPUNK/__main__.py
PopPUNK/assign.py
PopPUNK/bgmm.py
PopPUNK/citation.py
PopPUNK/dbscan.py
PopPUNK/info.py
PopPUNK/lineages.py
PopPUNK/mandrake.py
PopPUNK/models.py
PopPUNK/network.py
PopPUNK/plot.py
PopPUNK/qc.py
PopPUNK/reference_pick.py
PopPUNK/refine.py
PopPUNK/sketchlib.py
PopPUNK/sparse_mst.py
PopPUNK/trees.py
PopPUNK/utils.py
PopPUNK/visualise.py
docs/conf.py
docs/gpu.rst
test/test-gpu.py

- Replace depreciated `cudatoolkit` commands
- Fix memory management to avoid allocation errors
- Get GPU tests working
- Update GPU installation instructions

Updates for GPU analysis + documentation

---

PopPUNK/mandrake.py
PopPUNK/plot.py
PopPUNK/visualise.py

Also add as option to CLI for visualise

Increase default mandrake maxiter by 10x

---

PopPUNK/plot.py

Angle is now a kwarg (thanks and why)

API change in mpl380 ellipses

---

.github/workflows/docs_pr.yml
.github/workflows/docs_push.yml

Add actions for docs build

---

PopPUNK/visualise.py

This was accidently missed from last PR --> https://github.com/bacpop/PopPUNK/pull/342 .... missed the passing of the info_csv argument into `createMicroreact`

Pass info_csv into createMicroreact

---

PopPUNK/__init__.py
src/extend.cpp

Updated logic as otherwise `--count-unique-distances` had no effect.

Correction to counting distances for lineages
